### Explore gpuarray
- gpuarray objects act predictably and are in accordance with how NumPy arrays act. 
- We have to pull the output off the GPU with `get`
- Comparison between CPU and GPU computation time

In [1]:
import numpy as np
# Initialize PyCUDA
import pycuda.autoinit
from pycuda import gpuarray
from time import time

In [2]:
x_host = np.array([1,2,3], dtype=np.float32)
y_host = np.array([1,1,1], dtype=np.float32)
z_host = np.array([2,2,2], dtype=np.float32)

x_device = gpuarray.to_gpu(x_host)
y_device = gpuarray.to_gpu(y_host)
z_device = gpuarray.to_gpu(z_host)

In [3]:
x_host + y_host

array([2., 3., 4.], dtype=float32)

In [5]:
(x_device + y_device).get()

array([2., 3., 4.], dtype=float32)

In [6]:
x_host ** z_host

array([1., 4., 9.], dtype=float32)

In [7]:
(x_device ** z_device).get()

c:\Users\foonwong\AppData\Local\Programs\Python\Python310\lib\site-packages\pycuda\elementwise.py:47: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu

  return SourceModule(


array([1., 4., 9.], dtype=float32)

In [8]:
x_host / x_host

array([1., 1., 1.], dtype=float32)

In [9]:
(x_device / x_device).get()

c:\Users\foonwong\AppData\Local\Programs\Python\Python310\lib\site-packages\pycuda\elementwise.py:47: UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu

  return SourceModule(


array([1., 1., 1.], dtype=float32)

In [10]:
z_host - x_host

array([ 1.,  0., -1.], dtype=float32)

In [11]:
(z_device - x_device).get()

array([ 1.,  0., -1.], dtype=float32)

In [12]:
z_host / 2

array([1., 1., 1.], dtype=float32)

In [13]:
(z_device / 2).get()

array([1., 1., 1.], dtype=float32)

In [14]:
x_host - 1

array([0., 1., 2.], dtype=float32)

In [15]:
(x_device - 1).get()

array([0., 1., 2.], dtype=float32)